---
- name: Install packages
  pacman:
    name: [fcitx, fcitx-im, fcitx-configtool, fcitx-mozc]

- name: Copy environment file
  copy:
    src: environment
    dest: /etc/environment
    backup: true